In [49]:
#import drive dir
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [87]:
# import lib
import math
import os
import glob
import warnings
warnings.filterwarnings('ignore')
from tqdm.notebook import tqdm
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 999)
pd.set_option('display.max_colwidth', None)
from IPython.display import display_html
from itertools import chain,cycle

# infolib
def infolib(dataframe):
  
  def convert_size(size_bytes):
   if size_bytes == 0:
       return "0B"
   size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
   i = int(math.floor(math.log(size_bytes, 1024)))
   p = math.pow(1024, i)
   s = round(size_bytes / p, 2)
   return "%s %s" % (s, size_name[i])

  try:
      def get_df_name(dataframe):
        name =[x for x in globals() if globals()[x] is dataframe][0]
        return name

      Df_desc = {'dataset': [], 'columns': [], 'rows': [], 'row_duplicate':[], 'row_unique':[], 'row_whitout_NaN': [], 'row_whit_NaN':[], 'memory_usage':[]}
      # Total size in memory df.memory_usage(deep=True).sum() in bite 1112497
      # Variable types Numeric
      # # Variable types Categorical


      namedf=get_df_name(dataframe)
      Df_desc['dataset'].append(namedf)

      a=len(dataframe.columns)
      Df_desc['columns'].append(a)
      
      b=len(dataframe.index)
      Df_desc['rows'].append(b)
      
      c=len(dataframe.index)-len(dataframe.drop_duplicates())
      Df_desc['row_duplicate'].append(c)
      
      c=len(dataframe.index)-(len(dataframe.index)-len(dataframe.drop_duplicates()))
      Df_desc['row_unique'].append(c)
      
      d = len(dataframe.index)-dataframe.isna().sum().sum()
      Df_desc['row_whitout_NaN'].append(d)
      
      e = dataframe.isna().sum().sum()
      Df_desc['row_whit_NaN'].append(e)

      ea = dataframe.memory_usage(deep=True).sum()
      ea=convert_size(ea)
      Df_desc['memory_usage'].append(ea)

      DataFrames=pd.DataFrame.from_dict(Df_desc, orient='columns')
      DataFrames=DataFrames.set_index('dataset')
      DataFrames.index.name = None

      Tot_desc_num = {'feature_name': [], 'dtypes': [], 'count_not_NaN': [], 'count_NaN': [], 'unique':[],
                  'mean':[], 'std':[], 'min':[], 'max':[], '25%':[], '50%':[], '75%':[]}
      Tot_desc_cat = {'feature_name': [], 'dtypes': [], 'count_not_NaN': [], 'count_NaN': [], 'unique':[],
                  'top':[], 'freq':[]}
        
      for i in dataframe.columns:
        a=dataframe[i].dtypes
        
        if (a == int) or (a == float):
          Tot_desc_num['feature_name'].append(i)
          
          a=dataframe[i].dtypes
          Tot_desc_num['dtypes'].append(a)
          
          b=dataframe[i].count()
          Tot_desc_num['count_not_NaN'].append(b)
          
          c=dataframe[i].isna().sum()
          Tot_desc_num['count_NaN'].append(c)
          
          d = dataframe[i].nunique()
          Tot_desc_num['unique'].append(d)
          
          e=round(dataframe[i].mean(),3)
          Tot_desc_num['mean'].append(e)
          
          f=round(dataframe[i].std(),3)
          Tot_desc_num['std'].append(f)
          
          g=round(dataframe[i].min(),3)
          Tot_desc_num['min'].append(g)
          
          h=round(dataframe[i].max(),3)
          Tot_desc_num['max'].append(h)
          
          l=dataframe[i].quantile(0.25)
          Tot_desc_num['25%'].append(l)
          
          m=dataframe[i].quantile(0.5)
          Tot_desc_num['50%'].append(m)
          
          n=dataframe[i].quantile(0.75)
          Tot_desc_num['75%'].append(n)

        else:
          Tot_desc_cat['feature_name'].append(i)
          
          a=dataframe[i].dtypes
          Tot_desc_cat['dtypes'].append(a)
          
          b=dataframe[i].count()
          Tot_desc_cat['count_not_NaN'].append(b)
          
          c=dataframe[i].isna().sum()
          Tot_desc_cat['count_NaN'].append(c)
          
          d = dataframe[i].nunique()
          Tot_desc_cat['unique'].append(d)
          
          o=dataframe[i].value_counts().idxmax()
          Tot_desc_cat['top'].append(o)
          
          p=dataframe[i].value_counts()
          q=p.iloc[0]
          Tot_desc_cat['freq'].append(q)

      Numerical_Features=pd.DataFrame.from_dict(Tot_desc_num, orient='columns')
      Numerical_Features=Numerical_Features.set_index('feature_name')
      Numerical_Features.index.name = None

      Categorical_Features=pd.DataFrame.from_dict(Tot_desc_cat, orient='columns')
      Categorical_Features=Categorical_Features.set_index('feature_name')     
      Categorical_Features.index.name = None

      def display_side_by_side(*args,titles=cycle([''])):
          html_str=''
          for df,title in zip(args, chain(titles,cycle(['</br>'])) ):
              html_str+='<th style="text-align:center"><td style="vertical-align:top">'
              html_str+=f'<h3>{title}</h3>'
              html_str+=df.to_html().replace('table','table style="display:inline"')
              html_str+='</td></th></br></br>'
          display_html(html_str,raw=True)

      
      if not DataFrames.empty:
        if not Numerical_Features.empty:
          if not Categorical_Features.empty:
            display_side_by_side(DataFrames, Numerical_Features, Categorical_Features, titles=['DataFrame','Numeric Features', 'Categorical Features'])

      if not DataFrames.empty:
        if not Numerical_Features.empty:
          if Categorical_Features.empty:
            display_side_by_side(DataFrames, Numerical_Features, titles=['DataFrame','Numeric Features'])

      if not DataFrames.empty:
        if Numerical_Features.empty:
          if not Categorical_Features.empty:
            display_side_by_side(DataFrames, Categorical_Features, titles=['DataFrame', 'Categorical Features'])
      return
  except:
  
    print(f'Error: this is not a valid Pandas DataFrame')
    print(e)

In [88]:
# import lib
import os
import glob
import warnings
warnings.filterwarnings('ignore')
from tqdm.notebook import tqdm
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 999)
pd.set_option('display.max_colwidth', None) # setta il num. di caratteri visibili per ogni cella della colonna
# es. 50 = primi 50 caratteri
# None = testo completo
from IPython.display import display_html
from itertools import chain,cycle

In [89]:
# paths
drive_dir = '/content/drive/MyDrive/'
root = f'infolib/'
try:
  os.mkdir(f'{drive_dir}{root}')
  print(f'New path {root} created\n')
except Exception as e:
  print(e)
staging_path = f'staging/'
try:
  os.mkdir(f'{drive_dir}{root}{staging_path}')
  print(f'New path {staging_path} created\n')
except Exception as e:
  print(e)
staging = f'{drive_dir}{root}{staging_path}'

[Errno 17] File exists: '/content/drive/MyDrive/infolib/'
[Errno 17] File exists: '/content/drive/MyDrive/infolib/staging/'

In [95]:
# import file to pandas
df_01 = 'Chess_games_stats.csv'
df_02 = 'Conaf_Data_Chile_2017.csv'
df_03 = 'Student_Marks.csv'
df_04 = 'basic1.csv'
df_05 = 'data.csv'
df_06 = 'imdb_MOVIES.csv'
df_07 = 'xAPI_Edu_Data.csv'

# aggiungere titanic, petal, serie false e true, serie temporali

df_01 = pd.read_csv(f'{staging}{df_01}', index_col=[0])
df_02 = pd.read_csv(f'{staging}{df_02}', index_col=[0])
df_03 = pd.read_csv(f'{staging}{df_03}', index_col=[0])
df_04 = pd.read_csv(f'{staging}{df_04}', index_col=[0])
df_05 = pd.read_csv(f'{staging}{df_05}', index_col=[0])
df_06 = pd.read_csv(f'{staging}{df_06}', index_col=[0])
df_07 = pd.read_csv(f'{staging}{df_07}', index_col=[0])

df_list=[df_01, df_02, df_03, df_04, df_05, df_06, df_07]

In [94]:
infolib(df_02)