In [1]:
!pip install -i https://test.pypi.org/simple/ infolib

Looking in indexes: https://test.pypi.org/simple/
Collecting infolib
  Downloading https://test-files.pythonhosted.org/packages/b1/07/d230f6cc205d1981ab636bc54623112a0c726c6a5f1d5fbed3e162ccc24d/infolib-0.1.13-py3-none-any.whl (4.9 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from infolib) (5.4.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from infolib) (1.19.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from infolib) (1.1.5)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from infolib) (2019.12.20)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.7/dist-packages (from infolib) (8.12.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from infolib) (5.5.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (2.6.1)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (0.8.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (57.4.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (5.1.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (1.0.18)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (4.4.2)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (0.7.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->infolib) (1.15.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->infolib) (0.2.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->infolib) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->infolib) (2018.9)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->infolib) (0.7.0)
Installing collected packages: infolib
Successfully installed infolib-0.1.13

In [6]:
import numpy as np
import pandas as pd
from infolib.infolib import inf

In [7]:
!pip show infolib

Name: infolib
Version: 0.1.13
Summary: A small, simple and sturdy library to overview our PandasDataframe
Home-page: https://github.com/AntonelloManenti/infolib
Author: Antonello Manenti
Author-email: antonellomanenti@gmail.com
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: more-itertools, ipython, pandas, regex, numpy, psutil
Required-by:

In [8]:
test_01 = {'Text or mixed numeric/text': ['Lorem ipsum', 'Sed', 1], 'Floating point numbers': [0.2, 4.5442233, 1.3], 
     'Integer numbers': [0, 1, 12345], 
     'True/False values': [False, True, False], 'Date and time': [2000-1-2, 2000-1-3, 2000-1-4],
    'Differences between two datetimes': [np.nan, np.nan, np.nan], 'Finite list of text values': ['A', 'B', 'C'], 'NaN values':[np.nan, np.nan, np.nan]}
test_01 = pd.DataFrame.from_dict(test_01)

test_02 = ['a', 'b', 1, 3]

In [9]:
inf(test_01)

In [12]:
test_01['Finite list of text values'] = test_01['Finite list of text values'].astype('category')
test_01['Date and time']= pd.to_datetime(test_01['Date and time'])

In [13]:
inf(test_01)

In [42]:
a = test_01['Finite list of text values'].dtypes
b = test_01['Finite list of text values'].count()
c = test_01['Finite list of text values'].isna().sum()
d = test_01['Finite list of text values'].nunique()
e = test_01['Finite list of text values'].value_counts().idxmax()
f = test_01['Finite list of text values'].value_counts()
f = f.iloc[0]
g = []
for ii in test_01['Finite list of text values'].astype(str):
    h = len(ii)
    g.append(b)
ma = max(g)
mi = min(g)
print(f'dtype: {a}')
print(f'not_NaN: {b}')
print(f'NaN: {c}')
print(f'unique: {d}')
print(f'top: {e}')
print(f'freq: {f}')
print(f'ma_len: {ma}')
print(f'mi_len: {mi}')

dtype: category
not_NaN: 3
NaN: 0
unique: 3
top: C
freq: 1
ma_len: 3
mi_len: 3

In [59]:
a = len(test_01.columns)
b = len(test_01.index)
c = len(test_01.index)-len(test_01.drop_duplicates())
d = len(test_01.index)-(len(test_01.index)-len(test_01.drop_duplicates()))
e = len(test_01.index)-(len(test_01[test_01.isna().any(axis=1)].index))
f = len(test_01[test_01.isna().any(axis=1)].index)
g = test_01.memory_usage(deep=True, index=True).sum()
g = convert_size(g)

In [60]:
print(f'num_col: {a}')
print(f'num_row: {b}')
print(f'dup: {c}')
print(f'unique: {d}')
print(f'rows_duplicate: {e}')
print(f'rows_unique: {f}')
print(f'memory: {g}')

num_col: 8
num_row: 3
dup: 0
unique: 3
rows_duplicate: 0
rows_unique: 3
memory: 755.0 B

In [51]:
def convert_size(size_bytes):
  if size_bytes==0:
      return "0B"
  size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
  i = int(math.floor(math.log(size_bytes, 1024)))
  p = math.pow(1024, i)
  s = round(size_bytes / p, 2)
  return "%s %s" % (s, size_name[i])