In [1]:
!pip install -i https://test.pypi.org/simple/ infolib

Looking in indexes: https://test.pypi.org/simple/
Collecting infolib
  Downloading https://test-files.pythonhosted.org/packages/58/40/08868dc40c47edc5a122e18b13bccc225d68df18471e32a3fcaad3156b94/infolib-0.1.14-py3-none-any.whl (4.9 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from infolib) (5.5.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from infolib) (5.4.8)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from infolib) (2019.12.20)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from infolib) (1.19.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from infolib) (1.1.5)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.7/dist-packages (from infolib) (8.12.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (5.1.1)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (0.8.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (57.4.0)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (4.8.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (2.6.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (1.0.18)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->infolib) (4.4.2)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->infolib) (1.15.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->infolib) (0.2.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->infolib) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->infolib) (2018.9)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->infolib) (0.7.0)
Installing collected packages: infolib
Successfully installed infolib-0.1.14

In [2]:
import numpy as np
import pandas as pd
from infolib.infolib import inf

In [3]:
!pip show infolib

Name: infolib
Version: 0.1.14
Summary: A small, simple and sturdy library to overview our PandasDataframe
Home-page: https://github.com/AntonelloManenti/infolib
Author: Antonello Manenti
Author-email: antonellomanenti@gmail.com
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: regex, ipython, numpy, more-itertools, pandas, psutil
Required-by:

In [52]:
#pd.Dataframe test 1

test_01 = {'A': ['Lorem ipsum', 'Sed', 1], 'B': [0.2, 4.5442233, 1.3], 
  'C': [0, 1, 12345], 
  'D': [False, True, False], 'E': [2000, 2001, 2003],
  'F': [np.nan, np.nan, np.nan], 'G': ['A', 'B', 'C'], 'H':[np.nan, np.nan, np.nan]}

test_01 = pd.DataFrame.from_dict(test_01)

In [ ]:
#pd.Dataframe test 2 - no pd.Dataframe

test_02 = ['a', 'b', 1, 3]

In [53]:
#pd.Dataframe test 3 - all dtype

s = pd.Series(pd.date_range("2012-1-1", periods=3, freq="D"))
td = pd.Series([pd.Timedelta(days=i) for i in range(3)])
i = [1,2,3]
f = [0.123,423.231,0.002]
c = ['A', 'B', 'C']
cn = [1, 2, 3]
b = [False, True, False]
n = [np.nan, np.nan, np.nan]

test_03 = pd.DataFrame({"A": s, "B": td, "C": i, "D":f, "E":c, "F":cn, "G":b, "H":n})
test_03['E'] = test_03['E'].astype('category')
test_03['F'] = test_03['F'].astype('category')

In [54]:
inf(test_01)

In [55]:
inf(test_02)

This function expects PandasDataframe argument.
<class 'list'> is not a valid argument.

For more info about inf() visit https://github.com/AntonelloManenti/infolib

In [65]:
inf(test_03)